Initial containers + NavBar + watertracker prototype
Nvision-Nutrition/nvision pull request #7
Opened 2021-04-03 20:40 UTC by taylorsmart

- Created general containers on the index.js for key dashboard page components
- Added nav bar up top (not formatted aesthetically)
- Added water tracker prototype functionality

NOTE: The watertracker prototype is intentionally a switch statement in order to allow more flexibility with adding a variety of different container assets down the road.

2021-04-03 21:43 UTC, Scott-Guinn requested changes

2021-04-03 21:43 UTC, Scott-Guinn commented on components/caloricHistory.jsx
> +export default WaterHistory;
Is there a reason this file is named caloricHistory.jsx but the component is named WaterHistory?

2021-04-03 21:43 UTC, Scott-Guinn commented on components/dailyTracker.jsx
> +export default DailyTracker;
can we match casing in the file names as well as per react convention? "DailyTracker.jsx"

2021-04-03 21:43 UTC, Scott-Guinn commented on components/waterHistory.jsx
> +  const generateWaterGraph = (waterDrank = 62, waterGoal = 100) => {
Are these default values in here just for testing? If so, can we put a comment that says that so people know.

2021-04-03 21:43 UTC, Scott-Guinn commented on components/waterHistory.jsx
> +      0;
when would the waterGoal be less than/equal to 0?

2021-04-03 21:43 UTC, Scott-Guinn commented on components/waterHistory.jsx
> +    remainder = waterPercentage - remainder;
Might need to hop in a DC channel with you and have you step me through this. Can we combine these two lines and just set remainder = waterPercentage? Why are we subtracting 0 from it?

2021-04-03 21:43 UTC, Scott-Guinn commented on components/waterHistory.jsx
> +      0;
I would argue that this is redundant if we validate on entry and makes the code less readable.

2021-04-03 21:43 UTC, Scott-Guinn commented on components/waterHistory.jsx
> +      switch (remainder) {
for future implementation, I think best practices would be to use an if statement now and refactor to a switch down the road when it makes sense to do so. But lets see what your second reviewer thinks.

2021-04-04 00:04 UTC, emmaknor commented on components/caloricHistory.jsx
> +export default WaterHistory;
good question

2021-04-04 00:07 UTC, emmaknor commented on components/waterHistory.jsx
> +  const generateWaterGraph = (waterDrank = 62, waterGoal = 100) => {
Additionally, we shouldn't need default values if the input validation from the data entry team is set up correctly, but if this is for testing/initialization purposes no worries!

2021-04-04 00:10 UTC, emmaknor commented on components/waterHistory.jsx
> +    remainder = waterPercentage - remainder;
I too don't fully understand when the remainder is updated. Will this be stored as state?

2021-04-04 00:11 UTC, emmaknor commented on components/waterHistory.jsx
> +      switch (remainder) {
As of now it makes more sense to me to use an if statement; however, I do not know what your plans are for adding more containers as you stated previously. I am fine with this staying a switch statement for the time being and re-evaluating when the additional containers are implemented.

2021-04-04 00:13 UTC, emmaknor commented on pages/index.js
> +      <Navbar
Just to confirm as far as styling goes, we all plan to implement a dark theme for our MVP and then the light theme is our stretch goal?

2021-04-04 00:15 UTC, emmaknor commented on pages/index.js
> +            style={{
to keep styling consistent & stored in the same place it may be best to avoid inline styles & keep as much of our css as possible in the styles folder. it also may be a good idea to agree on some basic styling as a group so that our app stays cohesive as we flesh out our components.

2021-04-04 04:38 UTC, taylorsmart commented on components/caloricHistory.jsx
> +export default WaterHistory;
Error - was creating a storage location and forgot to change it.  Appreciate it!

2021-04-05 14:26 UTC, Scott-Guinn commented on pages/index.js
> +      <Navbar
I found dark/light theme to be exceptionally easy to implement in FEC so I don't think it's too much of a stretch to say we'd do both for MVP. Typically light theme is the standard so maybe we want to do that first.

2021-04-05 14:26 UTC, Scott-Guinn commented on pages/index.js
> +            style={{
^ I'm a culprit of this too, although for testing and development sometimes it's easier to use in-line styling and then go back and move it to a css file later.

2021-04-05 15:54 UTC, Scott-Guinn approved these changes

2021-04-05 15:55 UTC, merged